[package]
name = "sbpf-inline-asm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18.15"

[dev-dependencies]
solana-program-test = "1.18.15"
solana-sdk = "1.18.15"
tokio = { version = "1.35.1", features = ["full"] }